version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: converge_db
    restart: always
    environment:
      POSTGRES_USER: convergeuser
      POSTGRES_PASSWORD: convergepw
      POSTGRES_DB: convergedb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
